### Create user
POST http://localhost:5000/api/auth/createuser
Content-Type: application/json

{
    "name": "Hii",
    "email": "him@gmail.com",
    "password": "12345"
}

###

### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "him@gmail.com",
    "password": "12345"
}

###

### get user data
### Get User
POST http://localhost:5000/api/auth/getuser
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNmE0OTE4NDQxZDM1MjMzYTc4NmNmYzJmIn0sImlhdCI6MTc4MzE4MjU4OH0.QeQ-wEBb9B5S1J9xaU23_v1ca1zQSIPNGCW4e2W6WtY


###
### fetch all notes
GET http://localhost:5000/api/notes/fetchallnotes
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNmE0OTE4NDQxZDM1MjMzYTc4NmNmYzJmIn0sImlhdCI6MTc4MzE4MjU4OH0.QeQ-wEBb9B5S1J9xaU23_v1ca1zQSIPNGCW4e2W6WtY

###
### add a note
POST http://localhost:5000/api/notes/addnote
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNmE0OTE4NDQxZDM1MjMzYTc4NmNmYzJmIn0sImlhdCI6MTc4MzE4MjU4OH0.QeQ-wEBb9B5S1J9xaU23_v1ca1zQSIPNGCW4e2W6WtY

{
    "title": "Complete Today's Work",
    "description": "Lesss gooooo",
    "tag": "Personal"
}

###
### update Note
PUT http://localhost:5000/api/notes/updatenote/6a4b5b5209e54433c6d692ec
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNmE0OTE4NDQxZDM1MjMzYTc4NmNmYzJmIn0sImlhdCI6MTc4MzE4MjU4OH0.QeQ-wEBb9B5S1J9xaU23_v1ca1zQSIPNGCW4e2W6WtY

{
    "title": "My Title Updated",
    "description": "Just do your work. Updated",
    "tag": "Personal"
}


###
### delete note
DELETE http://localhost:5000/api/notes/deletenote/6a4a8f18570aa48de8be67a9
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNmE0OTE4NDQxZDM1MjMzYTc4NmNmYzJmIn0sImlhdCI6MTc4MzE4MjU4OH0.QeQ-wEBb9B5S1J9xaU23_v1ca1zQSIPNGCW4e2W6WtY